### ISSUE TITLE
 Unable to run employee-onboard-service-javaspring microservice

### ISSUE THREAD

**Issue by neeraj-lad** [airavata-courses/satyamsah#1]
Here is the crash log after running  `java -jar demo-0.0.1-SNAPSHOT.jar` inside `assignment1/employee-onboard-service-javaspring/target`.
https://pastebin.com/EX9R856x

**Comment by satyamsah** [comment]
give me sometime

**Comment by neeraj-lad** [comment]
Sorry, but it seems I am still facing the same issue. 
My system config:
`Mac OS X El Capitan
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)`
Let me know if you need any more details.

**Comment by satyamsah** [comment]
I have updated the codes as per your feedback and everything is running fine from my side

**Comment by neeraj-lad** [comment]
Yes, I am able to start the Java microservice now.
