### ISSUE TITLE
A couple of issues with 'create-employee.sql'

### ISSUE THREAD

**Issue by neeraj-lad** [airavata-courses/satyamsah#2]
1. There is a `use employee` command at the end. Should it not be `use employeedb`? Would you need to put it before creating the table 'employee'?

2. Another issue which I faced was:
`Operation CREATE USER failed for 'employeeuser'@'localhost'` 
Note that the user 'employeeuser' was created nonetheless. I am attaching the screenshot below.
<img width="797" alt="screen shot 2017-08-30 at 6 31 06 pm" src="https://user-images.githubusercontent.com/16287470/29898896-433611b6-8db6-11e7-86ce-68100c8ebe3b.png">

**Comment by satyamsah** [comment]
checked it. Somehow the system(or I) check-in previous version of project. I will let you know when I am done.

**Comment by satyamsah** [comment]
I am done with my changes, please go ahead:

Hi please drop the employee user using:
 DROP user 'employeeuser'@'localhost';
