### ISSUE TITLE
Assignment 1: Comments

### ISSUE THREAD

**Issue by tilaks26** [airavata-courses/satyamsah#6]
All three micro services work fine.
The UI calls the services directly as there is no API server that's been implemented.

Please implement an API server which exposes the services to the UI. The UI should hit the end point of the API server rather than the micro services directly. Please refer to the [lecture slides](http://courses.airavata.org/slides/SICE-Fall17-B649-Assignment-1.pdf) for more clarity.

**Comment by satyamsah** [comment]
So,in short do you mean to say that the static .html files should be hosted in the localhost:8080. Right, now the UI is is static.

**Comment by tilaks26** [comment]
Yes, host them. But the main thing is that there should be an API server that acts as a gateway between the UI and the microservices.

**Comment by satyamsah** [comment]
With respect to spring and node js services, the 'Spring Controller' class is acting as gateway to microservices.  But, yes, the python microservice module is directly contacting the database.

**Comment by tilaks26** [comment]
Please look at the following architecture -

<img width="1334" alt="screen shot 2017-09-08 at 4 50 49 pm" src="https://user-images.githubusercontent.com/13809837/30230833-027f2ee4-94b6-11e7-8aa9-a1b55215c390.png">

There is an API server (apart from the microservices) which acts as a gateway between the UI and the services. All the requests are routed to the gateway from UI. The gateway then routes the requests to the respective services. I hope you get the point now.

**Comment by satyamsah** [comment]
yes. Thanks.Got it.

**Comment by satyamsah** [comment]
gateway added. The gateway is running on port 8090

**Comment by tilaks26** [comment]
Satyam, you've have added a Gateway component but it is still not serving its purpose. The API Gateway is used to handle a request by invoking multiple microservices and aggregating the results and displaying it back to the UI.

What you are doing is just invoking the html pages from the Gateway which is wrong. In your code, you have 

<img width="989" alt="screen shot 2017-09-09 at 1 14 03 pm" src="https://user-images.githubusercontent.com/13809837/30242265-36b18990-9561-11e7-9017-6bb2720061d3.png">

where you are just calling the html stand-alone scripts from the gateway methods. Whereas, ideally you should redirect the requests to the endpoint of the gateway and the gateway will then redirect it to the respective microservices.

Also, can you please host the stand-alone html files on a server? You can look at @sachinkariyattin 's comment [here](https://github.com/airavata-courses/SinghPrasandeep/issues/3).

**Comment by satyamsah** [comment]
please check now. I have my API gateway is running at 9999 which is getting a requests from UI web-pages at running at 8090 and the same way getting the response.

**Comment by tilaks26** [comment]
Please resubmit your assignment 1 if you haven't already done so.

**Comment by satyamsah** [comment]
I have already  updated the github codebase with separate api-gateway server which you asked me to correct and  I already updated you with this in my last comment 4 days ago. So, Where else should I resubmit it, on canvas?

**Comment by tilaks26** [comment]
If you can still access the submit button on Canvas for Assignment 1, please resubmit. Or else, send a mail to the instructors (and CC the AIs) saying you have implemented what was requested and it will be regraded (do this only if you cannot resubmit to Canvas).
