### ISSUE TITLE
Assignment 2: Comments

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/satyamsah#9]
Hello Satyam,

1. I went through your Wiki and it seems like you have linked your RMQ using docker links. This defeats the purpose of microservices abstraction. With having a separate RMQ, we are de-coupling the RMQ. With docker links, you are constraining the RMQ to be on the same host as all the micro-services. 
The preferred way of using RMQ is not through Docker links but through using the Public IP of the RMQ while connecting to the Queue. I would suggest you to change your implementation to do the same.

2. The UI is hosted on http://129.114.17.65:8090/addemployee.html , but the jQuery redirects to localhost:9999/addEmployeeGateway which obviously results in an error. jQuery executes on client machine and as such it tries to find the Gateway on my local machine. It is fine to hardcode the Gateway IP in your UI since it is called over REST. Please change this so I can test if your application is working on the VMs.

3. Can you provide me some details on how your Jenkins setup is at the moment? I would suggest you email me the jenkins credentials so that I can review it as well.

**Comment by satyamsah** [comment]
1. There is an external RMQ as explained in the documentation. The reason of doing the linking is to connect one container with other and not hardcode ip in the code base each time we reproduce it on other server. Each time we change the RMQ server , we need to update in each microservice at code level to specify the ip address of new RMQ which I thought is not a good practice. Docker swarm lets if you want one container talk to another container on a different host(I am partially working on it). If you want me to hardcode the value of external MQs, I will do the same. 

2. I will change it. 

3. I will mail you the jenkins private key and target username.

**Comment by Ameya05** [comment]
You have a good point of not hardcoding the IP, but usually these values are all refactored out in configuration files which get picked up at build time. These configuration values are not hardcoded in the code level. Another thing to consider is that there is only 1 RMQ in the entire system and typically it will never be migrated from one server to another.

The higher level problem which lies in this is Service Discovery. Here in this setting, we are using a universally known RMQ IP address to discover all the services. As a result, the micro-services on X, Y & Z servers can still connect to the known IP address and provide continuous service.

Even in case of Docker swarm, one has a universally known Docker swarm manager node IP which will be used to join the swarm. For example the following code will be used by a Docker swarm worker node to join the manager node 
`docker swarm join \
    --token SWMTKN-1-49nj1cmql0jkz5s954yi3oex3nedyz0fb0xx14ie39trti4wxv-8vxv8rssmk743ojnwacrr2e7c \
    192.168.99.100:2377`

I hope this explanation helps.

**Comment by satyamsah** [comment]
Issue 1 and 2 got resolved. Kindly check the wiki.

**Comment by marpierc** [comment]
@satyamsah Please resubmit with the identified corrections.

**Comment by Ameya05** [comment]
Able to run it now. Also checked out Docker setup, looks good. Closing this issue.
